# dependencies:
#   - jupyter
#   - numpy
#   - matplotlib

channels:
- defaults
dependencies:
- python=3.6.6
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/15978945 
  - azureml-defaults==0.1.0.15978945 
  - azureml-pipeline-wrapper[notebooks]==0.1.0.15978945 
  - azureml-pipeline-core==0.1.0.15978945 
  - azure-storage-blob
  - torch==1.4.0
  - scikit-learn
  - tqdm