channels:
- defaults
dependencies:
- python=3.6.6
- pip:
  - --extra-index-url=https://azuremlsdktestpypi.azureedge.net/CLI-SDK-Runners-Validation/19134211
  - azureml-defaults==0.1.0.19134211
  - azureml-pipeline-wrapper==0.1.0.19134211
  - torch==1.4.0
  - scikit-learn
  - tqdm
  - pyarrow
  - inference-schema[numpy-support]
name: project_environment
